using DeviceServiceManager.Data;
using DeviceServiceManager.Models;
using MySqlConnector;
using System;
using System.Threading.Tasks;

namespace DeviceServiceManager.Repositories
{
    /// <summary>
    /// Handles direct database operations for the Address entity.
    /// </summary>
    public class AddressRepository
    {
        private readonly string _connectionString;

        /// <summary>
        /// Initializes a new instance of the <see cref="AddressRepository"/> class.
        /// </summary>
        public AddressRepository()
        {
            _connectionString = DatabaseConfig.GetConnectionString();
        }

        /// <summary>
        /// Inserts a new address into the database.
        /// </summary>
        /// <param name="address">The address object to insert.</param>
        /// <returns>The auto-generated database ID of the new address.</returns>
        public async Task<int> AddAsync(Address address)
        {
            // Parameterized query to prevent SQL injection
            string query = @"INSERT INTO adressen (strasse, hausnummer, plz, ort, land) 
                             VALUES (@Street, @HouseNumber, @ZipCode, @City, @Country);
                             SELECT LAST_INSERT_ID();";

            using (var connection = new MySqlConnection(_connectionString))
            {
                await connection.OpenAsync();

                using (var command = new MySqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@Street", address.Street);
                    command.Parameters.AddWithValue("@HouseNumber", address.HouseNumber);
                    command.Parameters.AddWithValue("@ZipCode", address.ZipCode);
                    command.Parameters.AddWithValue("@City", address.City);

                    // If no country is provided, default to 'Deutschland'
                    command.Parameters.AddWithValue("@Country", string.IsNullOrWhiteSpace(address.Country) ? "Deutschland" : address.Country);

                    // ExecuteScalar returns the ID generated by LAST_INSERT_ID()
                    var result = await command.ExecuteScalarAsync();
                    return Convert.ToInt32(result);
                }
            }
        }
    }
}